---
latitude: 40.75729
longitude: -73.98393
map_zoom: 12
name: Room Mate Grace Boutique Hotel
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 125 W 45th St
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10036'
_hotel_id: ROO197
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
